# pyproject.toml

[tool.black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --strict-markers --cov=app --cov-report=html --cov-report=term"
testpaths = [
    "tests",
    "app/tests",
]
python_files = [
    "test_*.py",
    "*_test.py"
]
markers = [
    "integration: marks tests as integration tests (require API keys)",
    "slow: marks tests as slow running",
]
